apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: web
        gitsha: "${GIT_SHA}"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  gitsha: "${GIT_SHA}"
                matchExpressions:
                  - {key: api, operator: In, values: [hello]}
              topologyKey: kubernetes.io/hostname
      containers:
      - name: hello-app
        image: ${DOCKER_IMAGE}
        imagePullPolicy: Always
        ports:
        - name: app-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: app-port
            httpHeaders:
            - name: X-Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: app-port
          periodSeconds: 10
