apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  template:
    metadata:
      labels:
        app: hello
        tier: web
        gitsha: "${GIT_SHA}"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  gitsha: "${GIT_SHA}"
                matchExpressions:
                  - {key: api, operator: In, values: [hello]}
              topologyKey: kubernetes.io/hostname
      containers:
      - name: hello-app
        image: ${DOCKER_IMAGE}
        ports:
        - containerPort: 8080
